version: 2

models:
  - name: stg_card_payments
    description: 'Limpeza inicial da tabela de pagamentos de cartão vinda do Python'
    columns:
      - name: payment_id
        description: 'Chave primária da transação'
        tests:
          - unique
          - not_null

      - name: amount_brl
        description: 'Valor bruto da transação'
        tests:
          - dbt_utils.expression_is_true:
              expression: "amount_brl > -5000"
              severity: warn